version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "filmsdb"
      POSTGRES_USER: "filmsuser"
      POSTGRES_PASSWORD: "passfordb"
    volumes:
      - filmsdb-data:/var/lib/postgresql/data
      - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"

  apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  filmsdb-data: